### PR TITLE
fix: support express@5 router

### LINKED ISSUE #57: split(...).join is not a function error with Express v5
I get the following error when running Express v5:
```
TypeError: split(...).join is not a function
        at ...\node_modules\@wesleytodd\openapi\lib\generate-doc.js:73:47
        at Array.forEach (<anonymous>)
        at iterateStack (...\node_modules\@wesleytodd\openapi\lib\generate-doc.js:71:24)
        at ...\node_modules\@wesleytodd\openapi\lib\generate-doc.js:17:5
        at Array.forEach (<anonymous>)
        at generateDocument (...\node_modules\@wesleytodd\openapi\lib\generate-doc.js:16:26)
        at OpenApiMiddleware (...\node_modules\@wesleytodd\openapi\index.js:41:29)
        at Layer.handleRequest (...\node_modules\express\node_modules\router\lib\layer.js:101:15)
        at trimPrefix (...\node_modules\express\node_modules\router\index.js:330:13)
        at ...\node_modules\express\node_modules\router\index.js:291:7
```
The split function seems to reach the last "complex" return case, giving a string instead of an array

### PR DESCRIPTION
**Pull request by wesleytodd**
Fixes #57, although I did not see the same error as reported. This does get the tests passing in with express@5 though.

### CODE REVIEW

**Review by Megapixel99 — APPROVED** [review]
The check for node 14 seems to be stuck on `npm it` (unsure if express 5 supports node 14), the code looks good though.

**Comment by wesleytodd** [comment]
I have had a few of my actions recently get stuck like this. I will wait a bit then give it a kick and see if a retry works. AFAIK these all should be supported. Express 5 supports back to node 4 I think, maybe technically even the code works as far back as 0.10.

**Comment by wesleytodd** [comment]
Ah, it is not express or node support, it is the npm which shipped with node 14 which does not support the aliases. I think that was npm 6. I will try it again with a newer npm.

**Comment by wesleytodd** [comment]
Ok, I decided to just drop node 14 since this is targeting the 1.x we can take the technically breaking change of note testing in node@14 but the code should still run despite the tests not passing.

**Pull request merged**
