### PR TITLE
Release/v1.0.0

### PR DESCRIPTION
**Pull request by wesleytodd**
Just wanted to put together a quick 1.0.0 plan. We have three breaking changes lined up:

- #52
- #50
- #59 (only breaking because it had to drop testing in node 14)

I was thinking maybe we should quickly tackle a few of the open issues as well before we release?

- #20: This one might require some work adding a test that covers it. (@AustinGil not sure if you are still using the package and/or want to help)
- #25: This should be relatively easy. If we wanted we could even generate the .d.ts files and test them (ex https://github.com/pkgjs/nv/pull/15). 
- #22: Also TS related, not sure I remember enough about this one to be sure what we need to do or if it is a reasonable ask.
- #19: This one maybe @AustinGil could comment on as well? Do we want this?

Maybe we don't need to land all this, most of these are non breaking and could go out after 1.0.0, but just wanted to see what folks thought.

### CODE REVIEW

**Comment by enov** [comment]
The section under [Note on package name](https://github.com/wesleytodd/express-openapi#note-on-package-name) should be fixed or removed. I don't that's accurate anymore.

**Comment by wesleytodd** [comment]
I was just thinking about that. I would be down for updating all the references in the readme to update that. That said, I still have hopes of being able to move this into the org and scope someday. But I totally agree that for now it is probably better to remove that.

**Comment by enov** [comment]
#55 Remove "Note on package name" and fix references

**Comment by wesleytodd** [comment]
I re-targeted #56 at this branch. First it had accidentally included the redoc breaking change in it and retargeting that resolves that. Secondly I think it is technically a breaking change despite the original way it was handled being entirely useless and this being a good feature addition. Just more safe to do since we plan a major very soon to bundle them together.

**Comment by Megapixel99** [comment]
I thought I had already re-targeted #56, unsure what changed its target...

**Comment by wesleytodd** [comment]
No worries, not a big deal, just wanted to make sure I called it out that I had changed it and why.

**Review by Megapixel99 — DISMISSED** [review]
LGTM

**Review by enov — APPROVED** [review]
@wesleytodd Please consider moving typescript issues/features outside of this PR scope, so that we can merge this. We can still work on them in another release.
Should we update the npm packages along the way? Thanks!

**Comment by wesleytodd** [comment]
Hey, really sorry to have left this hanging so long. I got a bit distracted with https://github.com/expressjs/discussions/issues/160. Since that is moving along now, I was going to propose we move this (finally) into the Express project and then we can get you folks on boarded as commiters (and likely project captains if you are interested). I really don't mean to be the bottleneck here, sorry.

I am working today to test out the next express version (which I will update the tests here with) and then I will try and release it asap. Again, really sorry for being the hold up here!

**Comment by wesleytodd** [comment]
Ok, so I added both support for testing with the two express majors and 5 is failing as reported in #57. I am going to fix that now and then publish if I finish it in time.

**Comment by wesleytodd** [comment]
I will leave that #59 open over night and release in the morning. Just want to give y'all a chance to try it out.

**Review by enov — APPROVED** [review]

**Review by Megapixel99 — APPROVED** [review]

**Comment by Megapixel99** [comment]
> Hey, really sorry to have left this hanging so long. I got a bit distracted with [expressjs/discussions#160](https://github.com/expressjs/discussions/issues/160). Since that is moving along now, I was going to propose we move this (finally) into the Express project and then we can get you folks on boarded as commiters (and likely project captains if you are interested). I really don't mean to be the bottleneck here, sorry.
> 
> I am working today to test out the next express version (which I will update the tests here with) and then I will try and release it asap. Again, really sorry for being the hold up here!

No worries, thank you for getting beck to us so quickly. I would be willing to help work on Express if more people are needed, unsure how long it would take for me to be able to contribute in any meaningful way.

**Comment by Megapixel99** [comment]
> I will leave that #59 open over night and release in the morning. Just want to give y'all a chance to try it out.

I did not find any issues when testing it.

**Comment by wesleytodd** [comment]
>  would be willing to help work on Express if more people are needed, unsure how long it would take for me to be able to contribute in any meaningful way.

@Megapixel99 Happy to have your help!! We are getting the governance and initial process stuff done now but will be needing folks who can help us steward all the different packages. Some need less work than others, so any help no matter how "meaningful" it might seem at first is for sure **meaningful**.

**Comment by Megapixel99** [comment]
> @Megapixel99 Happy to have your help!! We are getting the governance and initial process stuff done now but will be needing folks who can help us steward all the different packages. Some need less work than others, so any help no matter how "meaningful" it might seem at first is for sure **meaningful**.

Ok, sounds good. Feel free to ping me when you finish setting up the governance and initial process.

**Pull request merged**
