### PR TITLE
Remove Redoc from the Repo

### PR DESCRIPTION
**Pull request by Megapixel99**
Remove Redoc ui, routes, and tests from the Repo.

The desire to remove Redoc was indicated here: https://github.com/wesleytodd/express-openapi/pull/50#discussion_r1379485560 (as well as other places, potentially)

This PR makes backwards incompatible changes and should be reviewed thoroughly, as well as discussed, before approval.

### CODE REVIEW

**Comment by Megapixel99** [comment]
Upon pushing the same code from my fork https://github.com/Megapixel99/express-openapi/tree/remove-redoc to a branch with the same name in this repository, the tests seem to run and pass... I can re-create this PR from the `remove-redoc` branch in this repository if desired.

**Comment by wesleytodd** [comment]
Not necessary, but that is really weird. Anyway, since you have write here I am good with just pushing branches right here. We should try to clean them up after, which I know I am bad at lol. But not necessary for this one.

**Review by wesleytodd — CHANGES_REQUESTED** [review]
Only thing missing I think is removing it from the `package.json` right?

**Review by wesleytodd — APPROVED** [review]
Cool, so I am thinking maybe I land one more release on the pre 1.x with what is on main and then merge these after? And then maybe we do a beta release and decide if we want to land any more breaking changes before we push the `1.0.0`?

**Comment by Megapixel99** [comment]
Ok, sounds good.

**Pull request merged**
